# Config file for automatic testing at travis-ci.org

matrix:
  include:

    # REACT
    - language: node_js
      node_js:
        - "10"

      sudo: false
      before_script:
        - cd frontend
        - yarn install
        - yarn run build
      script:
        - yarn test

    # FLASK
    - language: python
      python:
        - 3.5
        - 3.6

      # Declare our environment variables
      before_script:
        - cd ..
        - export FLASK_APP=manage.py
        - export FLASK_DEBUG=1

      # Command to install dependencies
      install: pip install -r requirements.txt --no-cache-dir

      sudo: false

      # Run all flask tests
      script: pytest
